version: '3.8'

services:
  json-converter:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.json-converter.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.json-converter.tls=true"
      - "traefik.http.routers.json-converter.tls.certresolver=letsencrypt"
